version: "3"

services:
  solr4:
    image: msneddon/solr4.10
    expose:
      - 8983
    ports:
      - 8983:8983
    volumes:
      - ./solr4/cores:/cores

  search_service:
    build: search/.
    expose:
      - 7078
    ports:
      - 7078:7078
    links:
      - solr4
    volumes:
      - ./search/config:/kb/module/search/config
